from typing import Final

ALERT_DEDUP_HOURS: Final[int] = 24
ALERT_EXPIRE_DAYS: Final[int] = 7

RULE_THERMAL_HIGH: Final[str] = "RULE_THERMAL_HIGH"
RULE_RAINFALL_DEFICIT: Final[str] = "RULE_RAINFALL_DEFICIT"
RULE_FSI_HIGH: Final[str] = "RULE_FSI_HIGH"

RAINFALL_DEFICIT_ALERT_THRESHOLD: Final[float] = 0.70
FSI_HIGH_ALERT_THRESHOLD: Final[float] = 0.67
