"""Alert escalation engine constants — delivery only, not severity calculation."""

from app.core.constants.alert_severity import (
    SEVERITY_CRITICAL,
    SEVERITY_HIGH,
    SEVERITY_LOW,
    SEVERITY_MEDIUM,
)

# Alert lifecycle states
LIFECYCLE_CREATED = "CREATED"
LIFECYCLE_DELIVERED = "DELIVERED"
LIFECYCLE_ACKNOWLEDGED = "ACKNOWLEDGED"
LIFECYCLE_RESOLVED = "RESOLVED"

TERMINAL_LIFECYCLE = frozenset({LIFECYCLE_ACKNOWLEDGED, LIFECYCLE_RESOLVED})

# Escalation record status
ESCALATION_ACTIVE = "ACTIVE"
ESCALATION_STOPPED = "STOPPED"

STOP_REASON_ACKNOWLEDGED = "ACKNOWLEDGED"
STOP_REASON_RESOLVED = "RESOLVED"

# SMS delay timers (minutes)
SMS_DELAY_HIGH_MINUTES = 30
SMS_DELAY_CRITICAL_FARMER_MINUTES = 5
CONTACT_DELAY_CRITICAL_MINUTES = 30

# Quiet hours defaults (24h clock, local time)
DEFAULT_QUIET_HOURS_START = 22
DEFAULT_QUIET_HOURS_END = 6
DEFAULT_TIMEZONE = "Asia/Kolkata"

# Delivery channels
CHANNEL_IN_APP = "IN_APP"
CHANNEL_PUSH = "PUSH"
CHANNEL_SMS = "SMS"
CHANNEL_EMERGENCY_CONTACT = "EMERGENCY_CONTACT"

# Audit event types
EVENT_ALERT_CREATED = "ALERT_CREATED"
EVENT_SEVERITY_ASSIGNED = "SEVERITY_ASSIGNED"
EVENT_IN_APP_DELIVERED = "IN_APP_DELIVERED"
EVENT_PUSH_DELIVERED = "PUSH_DELIVERED"
EVENT_PUSH_DEFERRED = "PUSH_DEFERRED"
EVENT_PUSH_FAILED = "PUSH_FAILED"
EVENT_SMS_SENT = "SMS_SENT"
EVENT_SMS_FAILED = "SMS_FAILED"
EVENT_CONTACT_ESCALATION_SENT = "CONTACT_ESCALATION_SENT"
EVENT_CONTACT_ESCALATION_FAILED = "CONTACT_ESCALATION_FAILED"
EVENT_ESCALATION_STOPPED = "ESCALATION_STOPPED"
EVENT_RETRY = "RETRY"

# Tiers that receive push notifications
PUSH_TIERS = frozenset({SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL})

# Tiers subject to quiet hours
QUIET_HOURS_TIERS = frozenset({SEVERITY_LOW, SEVERITY_MEDIUM, SEVERITY_HIGH})
