from typing import Final

DISEASE_STATUS_CONFIRMED: Final[str] = "CONFIRMED_DISEASE"
DISEASE_STATUS_LOW_CONFIDENCE: Final[str] = "LOW_CONFIDENCE"
DISEASE_STATUS_REJECTED: Final[str] = "UNKNOWN"
DISEASE_STATUS_UNDETERMINED: Final[str] = "UNKNOWN"
DISEASE_STATUS_MEDIUM_CONFIDENCE: Final[str] = "LOW_CONFIDENCE"
DISEASE_STATUS_HIGH_CONFIDENCE: Final[str] = "CONFIRMED_DISEASE"

# New explicit outcomes
DISEASE_STATUS_INVALID_IMAGE: Final[str] = "INVALID_IMAGE"
DISEASE_STATUS_HEALTHY: Final[str] = "HEALTHY"
DISEASE_STATUS_UNKNOWN: Final[str] = "UNKNOWN"
DISEASE_STATUS_POSSIBLE_DISEASE: Final[str] = "POSSIBLE_DISEASE"
DISEASE_STATUS_CONFIRMED_DISEASE: Final[str] = "CONFIRMED_DISEASE"

DEFAULT_CONFIDENCE_THRESHOLD: Final[float] = 0.70
MAX_IMAGE_BYTES: Final[int] = 5 * 1024 * 1024
ALLOWED_IMAGE_TYPES: Final[frozenset[str]] = frozenset(
    {"image/jpeg", "image/png", "image/webp", "image/jpg"}
)
