from typing import Final

HORIZON_TODAY: Final[str] = "TODAY"
HORIZON_THIS_WEEK: Final[str] = "THIS_WEEK"
HORIZON_PREVENTIVE: Final[str] = "PREVENTIVE"

PRIORITY_EMERGENCY: Final[str] = "EMERGENCY"
PRIORITY_HIGH: Final[str] = "HIGH"
PRIORITY_MEDIUM: Final[str] = "MEDIUM"
PRIORITY_LOW: Final[str] = "LOW"

PRIORITY_RANK: Final[dict[str, int]] = {
    PRIORITY_LOW: 1,
    PRIORITY_MEDIUM: 2,
    PRIORITY_HIGH: 3,
    PRIORITY_EMERGENCY: 4,
}

CARD_RED: Final[str] = "RED"
CARD_YELLOW: Final[str] = "YELLOW"
CARD_GREEN: Final[str] = "GREEN"

TIMELINE_COPILOT_PLAN: Final[str] = "COPILOT_PLAN"
TIMELINE_COPILOT_ACTION: Final[str] = "COPILOT_ACTION"
TIMELINE_COPILOT_ACTION_COMPLETED: Final[str] = "COPILOT_ACTION_COMPLETED"
TIMELINE_YIELD_PROTECTION: Final[str] = "YIELD_PROTECTION"
