from typing import Final

COMPONENT_MAX: Final[float] = 25.0
SCORE_MAX: Final[float] = 100.0

BAND_PROTECTED: Final[str] = "PROTECTED"
BAND_MODERATE: Final[str] = "MODERATE"
BAND_AT_RISK: Final[str] = "AT_RISK"
BAND_CRITICAL: Final[str] = "CRITICAL"

BAND_THRESHOLD_PROTECTED: Final[float] = 75.0
BAND_THRESHOLD_MODERATE: Final[float] = 50.0
BAND_THRESHOLD_AT_RISK: Final[float] = 25.0

TREND_IMPROVING: Final[str] = "IMPROVING"
TREND_STABLE: Final[str] = "STABLE"
TREND_DECLINING: Final[str] = "DECLINING"
TREND_IMPROVING_DELTA: Final[float] = 5.0
TREND_DECLINING_DELTA: Final[float] = -5.0
TREND_LOOKBACK_DAYS: Final[int] = 7

COMPLIANCE_BASE: Final[float] = 25.0
COMPLIANCE_PENALTY_STALE_CRITICAL_ALERT: Final[float] = 10.0
COMPLIANCE_PENALTY_STALE_HIGH_ALERT: Final[float] = 8.0
COMPLIANCE_PENALTY_INCOMPLETE_TODAY_ACTION: Final[float] = 5.0
COMPLIANCE_BONUS_CRITICAL_ACTION_COMPLETE: Final[float] = 10.0
COMPLIANCE_BONUS_HIGH_ACTION_COMPLETE: Final[float] = 5.0
COMPLIANCE_STALE_ALERT_HOURS: Final[int] = 24
COMPLIANCE_STALE_ACTION_HOURS: Final[int] = 48
COMPLIANCE_COMPLETION_LOOKBACK_DAYS: Final[int] = 7

ALERT_BURDEN_HIGH_PENALTY: Final[float] = 8.0
ALERT_BURDEN_MEDIUM_PENALTY: Final[float] = 4.0
SEVERITY_RANK_PENALTY: Final[float] = 5.0

LOSS_PREVENTION_BAND_HIGH: Final[str] = "HIGH"
LOSS_PREVENTION_BAND_MODERATE: Final[str] = "MODERATE"
LOSS_PREVENTION_BAND_LOW: Final[str] = "LOW"
